### ISSUE TITLE
Chrome - Severe performance issue with scrolling and page-refresh

### ISSUE THREAD

**Issue by brianmhunt** [jschr/bootstrap-modal#152]
There is a potentially extraordinarily bad performance issue where the entire page will reload while scrolling.

It is [discussed on stackexhange](http://stackoverflow.com/questions/12969228), and here is a workaround that fixes it for bootstrap-modal:

``` css
/* div */.modal-scrollable {
  -webkit-transform: translateZ(0); 
}
```

Just thought I'd post this in case anyone else runs into it or it's innocuous enough to incorporate into the project - at least until [the issue](https://code.google.com/p/chromium/issues/detail?id=155313) is resolved.
