### ISSUE TITLE
Fixed height breaks due to !important in responsive rule

### ISSUE THREAD

**Issue by nealeu** [jschr/bootstrap-modal#249]
When using the height option, the Javascript correctly sets the modal-body style to "overflow:auto; height: 666px", but this rule does not take effect because of the !important in:

``` css
@media (max-width: 979px) {
    .modal-body,
    .modal-overflow .modal-body {
        position: static;
        margin: 0;
        height: auto !important;
        max-height: none !important;
        overflow: visible !important;
    }
}
```

Can the !important be avoided?  It's usually a bad idea.  Perhaps it is only needed for .modal-overflow ?
