### ISSUE TITLE
Aviary issue with .modal-open { 	 position: relative; }

### ISSUE THREAD

**Issue by Matt2012** [jschr/bootstrap-modal#52]
I'm using this library with the aviary image editing plugin. 

``` css
.modal-open {
     position: relative; /* safari */
         ..
}
```

This line was causing the aviary dialog to appear almost off the page at the bottom.
I've simply commented the line out and find safari seems ok without that line.
